# Generated by Django 5.2.7 on 2025-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('promo', 'Promotion'), ('info', 'Information'), ('alert', 'Alert')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
